### ISSUE TITLE
METS.xml cannot be processed properly with `ocrd/all:maximum` (ID: `2d9b243e9315`)

### ISSUE THREAD

**Issue by mweidling** [OCR-D/ocrd_all#392]
I tried to process to following workspace (as an example for the GTs used in Quiver) using Docker images of `ocrd/all`:

[alberti.zip](https://github.com/OCR-D/ocrd_all/files/12878563/alberti.zip)

When I try to process this workspace with an older version of `ocrd/all`, everything works fine, e.g.

`docker run --rm -v $PWD:/data ocrd/all:20-23-06-28 ocrd-olena-binarize -I OCR-D-IMG -O OCR-D-BIN -P impl sauvola`

yields the expected binarization.

Doing the same with `ocrd/all:maximum` (image ID `2d9b243e9315`) (`docker run --rm -v $PWD:/data ocrd/all:maximum ocrd-olena-binarize -I OCR-D-IMG -O OCR-D-BIN -P impl sauvola`) yield the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ocrd", line 33, in <module>
    sys.exit(load_entry_point('ocrd', 'console_scripts', 'ocrd')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/build/core/ocrd/ocrd/cli/validate.py", line 113, in validate_process
    _inform_of_result(validate_tasks([ProcessorTask.parse(t) for t in tasks],
  File "/build/core/ocrd/ocrd/task_sequence.py", line 115, in validate_tasks
    raise Exception("Invalid task sequence input/output file groups: %s" % report.errors)
Exception: Invalid task sequence input/output file groups: ["Input fileGrp[@USE='OCR-D-IMG'] not in METS!"]
```

Can you reproduce this behavior? `fileGrp[@USE='OCR-D-IMG']` is definitely part of the workspace's METS file, otherwise the first process would not have been successful.

**Comment by mweidling** [comment]
If it helps: I realized that the METS structure that is created with `docker run --rm -v $PWD:/data ocrd/all:maximum ocrd workspace init` plus adding the images as [described on our website](https://ocr-d.de/en/user_guide#non-existing-mets) differs from the METS structure I have in my workspace above. Processes using this newly created METS file work like a charm.

**Comment by MehmedGIT** [comment]
Any mets file which has only local but not remote URLs inside may cause the same issue. This is the case with the workspace you shared as well. It is something I observed with different workspaces too. Potentially it should be checked how to make the workspace-related code backward compatible. For now, I would suggest you rebuild the workspaces you use with their respective original mets file (that has remote URLs inside). The newer version of the core no longer replaces the remote URLs.
